### ISSUE TITLE
Test Node.js v18.17.0 bị lỗi như hình :)

### ISSUE THREAD

**Issue by 12520349** [CookieGMVN/MBBank#14]
C:\MBBANK\node_modules\mbbank\dist\index.js:142
    throw new Error(
          ^

Error: globalThis.crypto is not available, polyfill required (crypto.getRandomValues only)
    at C:\MBBANK\node_modules\mbbank\dist\index.js:142:11
    at Object.<anonymous> (C:\MBBANK\node_modules\mbbank\dist\index.js:588:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at C:\MBBANK\test.js:2:20
    at Object.<anonymous> (C:\MBBANK\test.js:7:3)

Node.js v18.17.0

**Comment by CookieGMVN** [comment]
@12520349 Hiện tại trong file `package.json` đã bắt buộc phải sử dụng engine node >=20.0 trở lên (để dùng thư viện có sẵn) rồi nhé bạn. Bạn cập nhật lên phiên bản node LTS mới nhất giúp mình.
